-- Revised SQL for direct analysis on cx.csv using DuckDB
-- Run with:
--   duckdb
--   .read revised_cx_analysis.sql

CREATE OR REPLACE VIEW customer_clean AS
SELECT
    "Customer ID" AS customer_id,
    Age AS age,
    Gender AS gender,
    "Item Purchased" AS item_purchased,
    Category AS category,
    "Purchase Amount (USD)" AS purchase_amount,
    Location AS location,
    Size AS size,
    Color AS color,
    Season AS season,
    "Review Rating" AS review_rating,
    "Subscription Status" AS subscription_status,
    "Shipping Type" AS shipping_type,
    "Discount Applied" AS discount_applied,
    "Promo Code Used" AS promo_code_used,
    "Previous Purchases" AS previous_purchases,
    "Payment Method" AS payment_method,
    "Frequency of Purchases" AS frequency_of_purchases,
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        WHEN Age BETWEEN 56 AND 65 THEN '56-65'
        ELSE '66+'
    END AS age_group
FROM read_csv_auto('cx.csv', header = true);

-- Q1. Total revenue generated by male vs. female customers
SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer_clean
GROUP BY gender
ORDER BY revenue DESC;

-- Q2. Customers who used a discount and still spent more than the average purchase amount
SELECT
    customer_id,
    purchase_amount
FROM customer_clean
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_clean)
ORDER BY purchase_amount DESC, customer_id;

-- Q3. Top 5 products with the highest average review rating
SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer_clean
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC, COUNT(*) DESC
LIMIT 5;

-- Q4. Average purchase amounts between Standard and Express shipping
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer_clean
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;

-- Q5. Compare average spend and total revenue between subscribers and non-subscribers
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_clean
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Top 5 products with the highest percentage of purchases with discounts applied
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer_clean
GROUP BY item_purchased
ORDER BY discount_rate DESC, COUNT(*) DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_clean
)
SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC, item_purchased
        ) AS item_rank
    FROM customer_clean
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank, item_purchased;

-- Q9. Are repeat buyers also likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_clean
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

-- Q10. Revenue contribution of each age group
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_clean
GROUP BY age_group
ORDER BY total_revenue DESC;
